### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data 

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.types

#### Creating a numpy array

In [1]:
# np.array

import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
# creating a 2D array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# creating a 3D matrix 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
a = np.array([1,2,3],dtype='int8')

In [5]:
a.dtype

dtype('int8')

In [6]:
# np.arange(start,end,step)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# np.ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# np.zeros
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((3,2))

array([[0.42506308, 0.57716227],
       [0.03192777, 0.35041414],
       [0.96718371, 0.9257102 ]])

In [11]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
a.ndim # tells the dimension of given matrix

2

In [14]:
a.shape

(3, 4)

In [15]:
a.size

12

In [16]:
a.itemsize

8

In [17]:
# changing Datatypes

In [18]:
a.dtype

dtype('float64')

In [19]:
# creating a 3D matrix 
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c.dtype

dtype('int32')

In [20]:
c.astype(np.int64)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int64)

In [21]:
c.dtype

dtype('int32')

#### Array Operations

In [22]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [23]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### Scaler Operator

In [25]:
# arithmetic operations
a1 *2 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [26]:
# relational operations
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
# vector operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [28]:
a1  * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Array functions

In [29]:
# max
np.max(a1)

11

In [30]:
# min 
np.min(a1)

0

In [31]:
# prod
np.prod(a1)

0

In [32]:
np.sum(a1)

66

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

In [34]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [37]:
# log 
np.log(a2)

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [36]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [39]:
np.random.random((2,3)) * 100

array([[83.576149  , 54.15666546, 22.39228129],
       [84.30733874, 16.81213286, 82.05889259]])

In [42]:
np.round(np.random.random((2,3))*100)

array([[56., 94., 70.],
       [50., 36., 80.]])

In [43]:
np.floor(np.random.random((2,3))*100)

array([[35., 22., 98.],
       [ 6.,  2., 42.]])

In [44]:
np.ceil(np.random.random((2,3))*100)

array([[36., 69., 28.],
       [29., 92., 20.]])

#### Iteration on Numpy array

In [48]:
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [51]:
for i in a2.ravel():
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


In [52]:
for i in np.nditer(a2):
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


#### Reshapping

In [57]:
a1 = a1.reshape(3,4)

In [59]:
a1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
np.transpose(a1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [62]:
# ravel converts ndimension to 1 dimension array 
a1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [66]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [69]:
np.hstack((a1,a2))

array([[12, 13, 14, 12, 13, 14],
       [15, 16, 17, 15, 16, 17],
       [18, 19, 20, 18, 19, 20],
       [21, 22, 23, 21, 22, 23]])

In [72]:
a = np.vstack((a1,a2))
a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [75]:
np.vsplit((a1),2)

[array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]

In [77]:
np.hsplit((a1.T),2)

[array([[12, 15],
        [13, 16],
        [14, 17]]),
 array([[18, 21],
        [19, 22],
        [20, 23]])]