#### Numpy array vs Python Lists

##### speed -->list

In [1]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time() - start)

1.4030137062072754


##### speed --> Numpy

In [3]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a+b

print(time.time()- start)

0.11879396438598633


In [4]:
# total times difference 
1.541440486907959/0.12083625793457031

12.756440105440943

##### memory

In [6]:
a = [i for i in range(100000000)]
import sys

sys.getsizeof(a)

835128600

In [13]:
a = np.array(100000000,dtype=np.int32)
sys.getsizeof(a)

100

#### Advance Indexing

In [16]:
# normal indexing and slicing 

a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
a[1,2]

5

In [50]:
# fancy Indexing 

a[[1,2,3]]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### Boolen Indexing

In [53]:
a = np.random.randint(1,100,24).reshape(6,4)

In [55]:
a

array([[58, 18, 78, 59],
       [48, 72, 38, 60],
       [77, 26, 28, 56],
       [15, 42, 25, 22],
       [63,  1, 27, 21],
       [33, 28, 73, 90]])

In [67]:
# find all the numbers which is greater than 50 
a[(a>50 ) & (a%2 == 0)]

array([58, 78, 72, 60, 56, 90])

In [77]:
a[a%7 == 0]

array([77, 28, 56, 42, 63, 21, 28])

#### BoradCasting in numpy 
The term broadcasting describers how Numpy treats array with different shape during arthmetic operations. THe smalller array is broadcast across the larger so that they have much compatiable shape

In [93]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print("matrix a is ")
print(a)
print("matrix b is ")
print(b)
print("matrix a  and b is ")
print(a+b)

matrix a is 
[[0 1 2]
 [3 4 5]]
matrix b is 
[[ 6  7  8]
 [ 9 10 11]]
matrix a  and b is 
[[ 6  8 10]
 [12 14 16]]


In [95]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [97]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
a+b

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

#### Working with mathematical function 

In [102]:
a = np.arange(10)

np.sum(a)

45

In [106]:
# sigmoid 
def sigmoid(array):
    return 1/(1 + np.exp(-(array)))
a = np.arange(20,100)
sigmoid(a)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
# mean squared error 
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)


In [132]:
a

73

In [134]:
b

array([[0, 1],
       [2, 3]])

In [152]:
def mse(actual, predicted):
    return np.mean((actual - predicted) ** 2)
print(mse(actual,predicted))

520.48


In [154]:
# make a function for binary cross entropy 


#### Work with missing values