#### np.sort 
return a sorted copy of an array

In [5]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([23, 47, 96, 23,  3, 25, 56, 13, 57, 14, 81, 97, 18, 19, 24])

In [6]:
np.sort(a)

array([ 3, 13, 14, 18, 19, 23, 23, 24, 25, 47, 56, 57, 81, 96, 97])

In [7]:
b = np.random.randint(1,100,24).reshape(4,6)
b

array([[58, 22, 21, 69, 24, 90],
       [29, 38, 78,  8, 98, 15],
       [25, 10, 65, 57, 82, 76],
       [63,  6, 10, 31, 14, 32]])

In [11]:
np.sort(b,axis=0)

array([[25,  6, 10,  8, 14, 15],
       [29, 10, 21, 31, 24, 32],
       [58, 22, 65, 57, 82, 76],
       [63, 38, 78, 69, 98, 90]])

In [12]:
np.sort(b,axis=1)

array([[21, 22, 24, 58, 69, 90],
       [ 8, 15, 29, 38, 78, 98],
       [10, 25, 57, 65, 76, 82],
       [ 6, 10, 14, 31, 32, 63]])

##### np.append
the numpy 

In [17]:
np.append(a,100)

array([ 23,  47,  96,  23,   3,  25,  56,  13,  57,  14,  81,  97,  18,
        19,  24, 100])

In [19]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[58., 22., 21., 69., 24., 90.,  1.],
       [29., 38., 78.,  8., 98., 15.,  1.],
       [25., 10., 65., 57., 82., 76.,  1.],
       [63.,  6., 10., 31., 14., 32.,  1.]])

In [35]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[58., 22., 21., 69., 24., 90.,  1.],
       [29., 38., 78.,  8., 98., 15.,  1.],
       [25., 10., 65., 57., 82., 76.,  1.],
       [63.,  6., 10., 31., 14., 32.,  1.]])

##### Concatenate
it concatenate a sequence of arrays along an existing axis

In [37]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)

print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


##### unique 

With the help of this function we can get the unique values from an array given as parameter in unique method 

In [39]:
np.unique(a)

array([ 3, 13, 14, 18, 19, 23, 24, 25, 47, 56, 57, 81, 96, 97])

##### expand_dims 

With the help of expand dims method we can get the expanded dimensions of an array 

In [43]:
np.expand_dims(a,axis=1)
a

array([23, 47, 96, 23,  3, 25, 56, 13, 57, 14, 81, 97, 18, 19, 24])

##### np.where 
the numpy where function returns the indices of element in an input array where the given condition is satisfied

In [47]:
np.where(a>50)

(array([ 2,  6,  8, 10, 11], dtype=int64),)

In [49]:
np.where(a>50,0,a)

array([23, 47,  0, 23,  3, 25,  0, 13,  0, 14,  0,  0, 18, 19, 24])

##### argmax
the numpy argmax function recturn the indices of the max element of the array in a praticlular axis

In [50]:
np.argmax(a)

11

In [51]:
a[11]

97

##### argmax
the numpy argmax function recturn the indices of the min element of the array in a praticlular axis

In [52]:
np.argmin(a)

4

##### np.cumsum
numpy.cumsum() function is used wjen we want to compute the cumulative sum of array element over a given axis

In [53]:
np.cumsum(a)

array([ 23,  70, 166, 189, 192, 217, 273, 286, 343, 357, 438, 535, 553,
       572, 596])

In [54]:
np.cumproduct(a)

array([         23,        1081,      103776,     2386848,     7160544,
         179013600,  1434827008,  1472881920, -1945076480, -1461266944,
        1896461824,  -726796800,  -197440512,   543597568,   161439744])