#### np.sort 
return a sorted copy of an array

In [1]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 5, 10, 67, 62, 38, 33, 54, 78, 28, 99, 29, 13, 94, 18, 31])

In [2]:
np.sort(a)

array([ 5, 10, 13, 18, 28, 29, 31, 33, 38, 54, 62, 67, 78, 94, 99])

In [3]:
b = np.random.randint(1,100,24).reshape(4,6)
b

array([[24, 88, 36, 91, 59, 65],
       [29, 38, 79, 49, 69, 72],
       [47, 34, 61, 81, 33, 58],
       [29, 54, 26, 32, 59, 51]])

In [4]:
np.sort(b,axis=0)

array([[24, 34, 26, 32, 33, 51],
       [29, 38, 36, 49, 59, 58],
       [29, 54, 61, 81, 59, 65],
       [47, 88, 79, 91, 69, 72]])

##### np.append
the numpy 